name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-hacs:
    name: Validate HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    name: Validate with hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: hassfest
        uses: home-assistant/actions/hassfest@master
